apiVersion: v1
kind: Pod
metadata:
  name: test-env
spec:
  containers:
    - name: test-env-sh
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: GUNICORN_WORKERS
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: tracker-gunicorn
              # Specify the key associated with the value
              key: workers
        - name: GUNICORN_TIMEOUT
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: tracker-gunicorn
              # Specify the key associated with the value
              key: timeout
  restartPolicy: Never
